"""
Abstract Classes for Resume Optimization Pipeline

Architecture:
  Pipeline 1: Ideal Candidate Generation (Strong LLM)
  Pipeline 2: Unbiased Skill Retrieval (Algorithm-based)
  Comparison: Gap Analysis + Grading Framework
  Generation: Iterative Optimization (Weak LLM)
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Any
from enum import Enum


# ═══════════════════════════════════════════════════════════════════
# ENUMS
# ═══════════════════════════════════════════════════════════════════

class MatchStrength(Enum):
    """Strength of match between user skill and ideal requirement"""
    EXACT = "exact"           # Direct match
    STRONG = "strong"         # Semantically equivalent
    PARTIAL = "partial"       # Related but not complete
    WEAK = "weak"             # Tangentially related
    NONE = "none"             # No match


class SkillCategory(Enum):
    """Categories of skills/experiences"""
    TECHNICAL = "technical"
    SOFT_SKILL = "soft_skill"
    EXPERIENCE = "experience"
    ACHIEVEMENT = "achievement"
    EDUCATION = "education"
    CERTIFICATION = "certification"
    PROJECT = "project"


# ═══════════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════

@dataclass
class IdealRequirement:
    """Single requirement from ideal candidate profile"""
    description: str
    category: SkillCategory
    priority: float  # 0.0 to 1.0, higher = more important
    keywords: List[str] = field(default_factory=list)
    context: str = ""


@dataclass
class IdealCandidateProfile:
    """Generated by strong LLM from job description - serves as grading rubric"""
    requirements: List[IdealRequirement]
    role_summary: str
    experience_level: str
    industry_context: str
    source_job_description: str


@dataclass
class RetrievedSkill:
    """Single user skill/sentence from unbiased retrieval"""
    text: str
    category: SkillCategory
    source_id: str  # Reference to original data
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MatchResult:
    """Single match between ideal requirement and user skill"""
    requirement: IdealRequirement
    user_skill: Optional[RetrievedSkill]
    strength: MatchStrength
    explanation: str = ""


@dataclass
class GapAnalysis:
    """Comparison result between ideal and user's actual skills"""
    matches: List[MatchResult]      # Requirements user satisfies
    gaps: List[MatchResult]         # Requirements user lacks
    redundancies: List[Tuple[RetrievedSkill, RetrievedSkill, str]]  # (skill1, skill2, why_redundant)
    
    @property
    def match_count(self) -> int:
        return len([m for m in self.matches if m.strength != MatchStrength.NONE])
    
    @property
    def gap_count(self) -> int:
        return len(self.gaps)
    
    @property
    def coverage_ratio(self) -> float:
        total = self.match_count + self.gap_count
        if total == 0:
            return 0.0
        return self.match_count / total


@dataclass
class GradingCriterion:
    """Single criterion in grading framework"""
    name: str
    weight: float  # 0.0 to 1.0
    description: str
    satisfied_by: Optional[RetrievedSkill] = None
    is_gap: bool = False


@dataclass
class GradingFramework:
    """Structured rubric for weak LLM to iterate against"""
    criteria: List[GradingCriterion]
    gap_analysis: GapAnalysis
    ideal_reference: IdealCandidateProfile
    
    def get_score(self) -> float:
        """Calculate weighted score based on satisfied criteria"""
        total_weight = sum(c.weight for c in self.criteria)
        if total_weight == 0:
            return 0.0
        satisfied_weight = sum(c.weight for c in self.criteria if not c.is_gap)
        return satisfied_weight / total_weight


@dataclass
class OptimizationResult:
    """Result from iterative generation"""
    optimized_resume: str
    matches_report: List[Dict]      # What user HAS
    gaps_report: List[Dict]         # What user is MISSING
    redundancies_removed: List[str]
    iterations_used: int
    final_score: float


# ═══════════════════════════════════════════════════════════════════
# ABSTRACT CLASSES
# ═══════════════════════════════════════════════════════════════════

class IdealCandidateGenerator(ABC):
    """
    Pipeline 1: Strong LLM generates ideal candidate profile
    
    This creates the "grading rubric" - what a perfect candidate looks like.
    Should be run with a strong model (e.g., Qwen 32B) for accuracy.
    """
    
    @abstractmethod
    def generate_ideal(self, job_description: str) -> IdealCandidateProfile:
        """
        Parse job description and generate ideal candidate profile.
        
        Args:
            job_description: Raw job posting text
            
        Returns:
            IdealCandidateProfile with prioritized requirements
        """
        pass
    
    @abstractmethod
    def extract_keywords(self, text: str) -> List[str]:
        """Extract relevant keywords from text"""
        pass


class UnbiasedRetriever(ABC):
    """
    Pipeline 2: Retrieve ALL relevant user skills without scoring bias
    
    This should return the complete inventory of applicable skills.
    NO optimization, NO coverage calculation - just retrieval.
    """
    
    @abstractmethod
    def retrieve_all(
        self, 
        user_skills: List[Dict],  # User's stored skills/sentences
        job_context: str           # For relevance filtering only
    ) -> List[RetrievedSkill]:
        """
        Get complete inventory of user's applicable skills.
        
        Args:
            user_skills: All user's stored skills/experiences
            job_context: Job description for basic relevance
            
        Returns:
            List of all potentially relevant skills (unbiased)
        """
        pass
    
    @abstractmethod
    def categorize_skill(self, skill_text: str) -> SkillCategory:
        """Categorize a skill/experience into appropriate type"""
        pass


class GapAnalyzer(ABC):
    """
    Comparison phase: Analyze what matches and what's missing
    
    Compares ideal candidate profile against retrieved user skills.
    Identifies matches, gaps, and redundancies.
    """
    
    @abstractmethod
    def analyze(
        self, 
        ideal: IdealCandidateProfile, 
        retrieved: List[RetrievedSkill]
    ) -> GapAnalysis:
        """
        Compare ideal vs actual skills.
        
        Args:
            ideal: Profile from strong LLM
            retrieved: User's retrieved skills (unbiased)
            
        Returns:
            GapAnalysis with matches, gaps, redundancies
        """
        pass
    
    @abstractmethod
    def calculate_match_strength(
        self,
        requirement: IdealRequirement,
        skill: RetrievedSkill
    ) -> Tuple[MatchStrength, str]:
        """
        Determine how well a skill matches a requirement.
        
        Returns:
            Tuple of (strength, explanation)
        """
        pass
    
    @abstractmethod
    def detect_redundancies(
        self,
        skills: List[RetrievedSkill]
    ) -> List[Tuple[RetrievedSkill, RetrievedSkill, str]]:
        """
        Find redundant skills that say the same thing.
        
        Returns:
            List of (skill1, skill2, reason) tuples
        """
        pass
    
    @abstractmethod
    def create_grading_framework(
        self, 
        ideal: IdealCandidateProfile,
        gap_analysis: GapAnalysis
    ) -> GradingFramework:
        """
        Create structured rubric for weak LLM.
        
        Args:
            ideal: Reference profile
            gap_analysis: What matches and what's missing
            
        Returns:
            GradingFramework for iterative optimization
        """
        pass


class IterativeGenerator(ABC):
    """
    Generation phase: Weak LLM iterates against grading framework
    
    Uses a lighter model (e.g., Llama 1.8B) that can iterate quickly.
    Guided by the grading framework created from strong LLM's ideal profile.
    """
    
    @abstractmethod
    def generate(
        self,
        retrieved_skills: List[RetrievedSkill],
        grading_framework: GradingFramework,
        max_iterations: int = 5
    ) -> OptimizationResult:
        """
        Iterate to optimize resume against framework.
        
        Constraints:
          - Avoid redundancy
          
        Args:
            retrieved_skills: User's unbiased skill inventory
            grading_framework: Rubric from gap analysis
            max_iterations: Max optimization iterations
            
        Returns:
            OptimizationResult with resume, matches, gaps, etc.
        """
        pass
    
    @abstractmethod
    def score_iteration(
        self,
        current_resume: str,
        grading_framework: GradingFramework
    ) -> float:
        """Score current resume against grading framework"""
        pass


# ═══════════════════════════════════════════════════════════════════
# ORCHESTRATOR
# ═══════════════════════════════════════════════════════════════════

class ResumeOptimizationPipeline:
    """
    Full pipeline orchestrator
    
    Combines all components:
      1. Strong LLM → Ideal Candidate Profile
      2. Unbiased Retrieval → User's Skills
      3. Gap Analysis → Grading Framework
      4. Weak LLM Iteration → Optimized Resume
    """
    
    def __init__(
        self,
        ideal_generator: IdealCandidateGenerator,
        retriever: UnbiasedRetriever,
        analyzer: GapAnalyzer,
        generator: IterativeGenerator
    ):
        self.ideal_generator = ideal_generator
        self.retriever = retriever
        self.analyzer = analyzer
        self.generator = generator
    
    def optimize(
        self, 
        user_skills: List[Dict], 
        job_description: str
    ) -> Dict[str, Any]:
        """
        Run full optimization pipeline.
        
        Args:
            user_skills: User's stored skills/experiences
            job_description: Target job posting
            
        Returns:
            Dict with resume, matches, gaps, ideal_reference, iterations
        """
        # Pipeline 1: Strong LLM creates ideal candidate
        ideal = self.ideal_generator.generate_ideal(job_description)
        
        # Pipeline 2: Unbiased retrieval of user skills
        retrieved = self.retriever.retrieve_all(user_skills, job_description)
        
        # Comparison: Create grading framework
        gap_analysis = self.analyzer.analyze(ideal, retrieved)
        grading_framework = self.analyzer.create_grading_framework(ideal, gap_analysis)
        
        # Generation: Weak LLM iterates
        result = self.generator.generate(retrieved, grading_framework)
        
        return {
            "resume": result.optimized_resume,
            "matches": result.matches_report,
            "gaps": result.gaps_report,
            "redundancies_removed": result.redundancies_removed,
            "ideal_reference": ideal,
            "gap_analysis": gap_analysis,
            "grading_framework": grading_framework,
            "iterations": result.iterations_used,
            "final_score": result.final_score
        }
